export const ACTION_TYPE = {
    PRODUCTS_FETCH_REQUEST:"PRODUCTS_FETCH_REQUEST",
    PRODUCTS_FETCH_SUCCSESS :"PRODUCTS_FETCH_SUCCSESS",
    PRODUCTS_FETCH_FAILED:"PRODUCTS_FETCH_FAILED",

    PRODUCTS_SEND_REQUEST:"PRODUCTS_SEND_REQUEST",
    PRODUCTS_SEND_SUCCSESS:"PRODUCTS_SEND_SUCCSESS",
    PRODUCTS_SEND_FAILED:"PRODUCTS_SEND_FAILED",

    PRODUCTS_ADD_TO_CART:"PRODUCTS_ADD_TO_CART",
    DELETE_PRODUCT_CART:"DELETE_PRODUCT_CART",
    DECREASE_PRODUCT_CART:"DECREASE_PRODUCT_CART",
    INCREASE_PRODUCT_CART:"INCREASE_PRODUCT_CART",

    RESET_ACTION:"RESET_ACTION",
}